### PR TITLE
setReadTimeout does not apply timeout if none set

### PR DESCRIPTION
**Pull request by OnlyInAmerica**
Per #3 , the root issue appears to be that if no `readTimeout` is set in `nflog.Config` the result will be a call to `nflog.Con.SetReadDeadline(time.Now())`.

Perhaps a better default behavior is to refrain from setting a read deadline in the absence of a `nflog.Config.readTimeout`?

### CODE REVIEW

**Comment by florianl** [comment]
Thank you for contributing!

Seeing the logs in https://github.com/florianl/go-nflog/issues/3 I agree with you.

Maybe, we can just make sure, that `nflog.readTimeout` is set to something bigger than 0 in [Open()](https://github.com/florianl/go-nflog/blob/master/nflog.go#L42), rather than doing this every time in `setReadTimeout()`. Can you update your PR?

**Comment by OnlyInAmerica** [comment]
No problem!

I think moving this behavior to `Open()` would require deciding on some default timeout? For example:
```
if config.ReadTimeout > 0 {
    nflog.readTimeout = config.ReadTimeout
} else {
    nflog.readTimeout = time.Duration(math.MaxInt64) // don't timeout
}
```
Alternatively, could we move [`nflog.setReadTimeout()`](https://github.com/florianl/go-nflog/blob/master/nflog.go#L183) from `Register()` to `Open()`? It feels like in absence of a readTimeout, the standard library behavior should suffice. That is unless we need to be setting readTimeout before each call to `nflog.Con.Receive()`.

**Comment by florianl** [comment]
A more elegant way might be, to change the value `nflog.readTimeout` to a function - just like `nflog.setReadTimeout()`.
Then, if `config.ReadTimeout` is set to something other than `0`, this function can be initialized with this value in `Open()`. Otherwise, this function will just be an empty function.
And in  `Register()`, the existing call of `nflog.setReadTimeout()` can just be replaced with this new function.
This way, we avoid checking the config value multiple times. And, if no value is configured for `config.ReadTimeout`, the receiving blocks till a information is received from nflog - this can be a use case for some users I think.

**Comment by florianl** [comment]
In https://github.com/florianl/go-nfqueue/commit/b85ba059abac82bc1ab9a1ad4405574a19c163ff I have implemented the improved read/write timeout handling.

Can you update your PR?

**Comment by florianl** [comment]
Thank you for contributing this change!

**Pull request merged**
