### PR TITLE
change Log struct to interface

### LINKED ISSUE #21: Logging uses interfaces instead of structs
Logger and caller's logger cannot be used together.

```
type Logger interface {
        Prinft(args ...string)
}

type Config struct {
         ...
	// Interface to log internals.
	Logger Logger
}
```

### PR DESCRIPTION
**Pull request by chinazj**
fix #21

### CODE REVIEW

**Comment by chinazj** [comment]
@florianl thanks

**Comment by florianl** [comment]
This is a breaking change. Please elaborate more in https://github.com/florianl/go-nflog/issues/21 why [*log.Logger](https://pkg.go.dev/log#Logger) doesn't work.

**Comment by chinazj** [comment]
I added some info in #21 . please check it. thanks

**Comment by florianl** [comment]
Closing PR - see https://github.com/florianl/go-nflog/issues/21#issuecomment-1065146334 for reason.

**Pull request closed without merging**
